apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
spec:
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: devopsedu/employee
        ports:
        - containerPort: 8888
        env:
        - name: MONGO_URI
          value: "mongodb://mongo:27017/employee"
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  type: NodePort
  selector:
    app: nodejs-app
  ports:
  - port: 8888
    targetPort: 8888
    nodePort: 30007
